/* Program.cs
 * 
 * This is generated by Visual Studio to run the main program
 * 
 * Created By: Ankit Sadana
 * Created On: 11/29/2014
 * Last Modified By: Ankit Sadana
 * Last Modified On: 12/07/2014
 * 
 * IU Username: asadana
 * 
 * Final Project for A590
 * Part of: findMyColor Project
 */

// Libraries included for this form
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;

// Name of the project: findMyColor
namespace findMyColor
{
    // Main class for this project
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        // Main function that runs our program
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            // Runs the Welcome Screen form
            Application.Run(new welcomeForm());
            // Runs the Main Game form after the welcome screen is closed
            Application.Run(new mainGame());
        }
    }
}
